import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import Banner from './components/Banner';
import Features from './components/Gallery';

export const metadata = {
	title: 'Ketchen',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				<Banner />
				<Features />
				<Footer />
			</body>
		</html>
	);
}
